.\"                                      Hey, EMACS: -*- nroff -*-
.TH CYCLICTEST 8 "december  20, 2007"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
cyclictest \- High resolution test program
.SH SYNOPSIS
.B cyclictest
.RI "[ \-hfmnqrsvMS ] [\-a " proc " ] [\-b " usec " ] [\-c " clock " ] [\-d " dist " ] \
[\-h " histogram " ] [\-i " intv " ] [\-l " loop " ] [\-o " red " ] [\-p " prio " ] \
[\-t " num " ] [\-D " time "] [\-w] [\-W] [\-y " policy "]"

.\" .SH DESCRIPTION
.\" This manual page documents briefly the
.\" .B cyclictest commands.
.\" .PP
.\" \fI<whatever>\fP escape sequences to invode bold face and italics, respectively.
.\" \fBcyclictest\fP is a program that...
.SH OPTIONS
These programs follow the usual GNU command line syntax, with long
options starting with two dashes ('\-\-').
.br
A summary of options is included below.
.\" For a complete description, see the Info files.
.TP
.B \-a, \-\-affinity[=PROC]
Run all threads on procesor number PROC. If PROC is not specified, run thread #N on processor #N.
.TP
.B \-b, \-\-breaktrace=USEC
Send break trace command when latency > USEC. This is a debugging option to control the latency tracer in the realtime preemption patch.
It is useful to track down unexpected large latencies on a system. This option does only work with following kernel config options.

    For kernel < 2.6.24:
.br
    * CONFIG_PREEMPT_RT=y
.br
    * CONFIG_WAKEUP_TIMING=y
.br
    * CONFIG_LATENCY_TRACE=y
.br
    * CONFIG_CRITICAL_PREEMPT_TIMING=y
.br
    * CONFIG_CRITICAL_IRQSOFF_TIMING=y
.sp 1
    For kernel >= 2.6.24:
.br
    * CONFIG_PREEMPT_RT=y
.br
    * CONFIG_FTRACE
.br
    * CONFIG_IRQSOFF_TRACER=y
.br
    * CONFIG_PREEMPT_TRACER=y
.br
    * CONFIG_SCHED_TRACER=y
.br
    * CONFIG_WAKEUP_LATENCY_HIST


kernel configuration options enabled. The USEC parameter to the \-b option defines a maximum latency value, which is compared against the actual latencies of the test. Once the measured latency is higher than the given maximum, the kernel tracer and cyclictest is stopped. The trace can be read from /proc/latency_trace. Please be aware that the tracer adds significant overhead to the kernel, so the latencies will be much higher than on a kernel with latency tracing disabled.
.TP
.B \-c, \-\-clock=CLOCK
Selects the clock, which is used:

    * 0 selects CLOCK_MONOTONIC, which is the monotonic increasing system time (default).
    * 1 selects CLOCK_REALTIME, which is the time of day time.

CLOCK_REALTIME can be set by settimeofday, while CLOCK_MONOTONIC can not be modified by the user.
This option has no influence when the \-s option is given.
.TP
.B \-C, \-\-context
context switch tracing (used with \-b)
.TP
.B \-d, \-\-distance=DIST
Set the distance of thread intervals in microseconds (default is 500us). When cyclictest is called with the \-t option and more than one thread is created, then this distance value is added to the interval of the threads: Interval(thread N) = Interval(thread N\-1) + DIST
.TP
.B \-E, \-\-event
event tracing (used with \-b)
.TP
.B \-f, \-\-ftrace
Enable function tracing using ftrace as tracer. This option is available only with \-b.
.TP
.B \-h, \-\-histogram=MAXLATENCYINUS
Dump latency histogram to stdout. US means the max time to be be tracked in microseconds. When you use \-h option to get histogram data, Cyclictest runs many threads with same priority without priority\-\-.
.TP
.B \-i, \-\-interval=INTV
Set the base interval of the thread(s) in microseconds (default is 1000us). This sets the interval of the first thread. See also \-d.
.TP
.B \-l, \-\-loops=LOOPS
Set the number of loops. The default is 0 (endless). This option is useful for automated tests with a given number of test cycles. Cyclictest is stopped once the number of timer intervals has been reached.
.TP
.B \-n, \-\-nanosleep
Use clock_nanosleep instead of posix interval timers. Setting this option runs the tests with clock_nanosleep instead of posix interval timers.
.TP
.B \-N, \-\-nsecs
Show results in nanoseconds instead of microseconds, which is the default unit.
.TP
.B \-o, \-\-oscope=RED
Oscilloscope mode, reduce verbose output by RED.
.TP
.B \-O, \-\-traceopt=TRACING_OPTION
Used to pass tracing options to ftrace tracers. May be invoked mutiple
times for multiple trace options. For example trace options look at /sys/kernel/debug/tracing/trace_options
.TP
.B \-p, \-\-prio=PRIO
Set the priority of the first thread. The given priority is set to the first test thread. Each further thread gets a lower priority:
Priority(Thread N) = max(Priority(Thread N\-1) \- 1, 0)
.TP
.B \-q, \-\-quiet
Run the tests quiet and print only a summary on exit. Useful for automated tests, where only the summary output needs to be captured.
.TP
.B \-r, \-\-relative
Use relative timers instead of absolute. The default behaviour of the tests is to use absolute timers. This option is there for completeness and should not be used for reproducible tests.
.TP
.B \-s, \-\-system
Use sys_nanosleep and sys_setitimer instead of posix timers. Note, that \-s can only be used with one thread because itimers are per process and not per thread. \-s in combination with \-n uses the nanosleep syscall and is not restricted to one thread.
.TP
.B \-T, \-\-tracer=TRACEFUNC
set the ftrace tracer function. Used with the \-b option. Must be one
of the trace functions available from <debugfs-mountpoint>/kernel/debug/tracing/available_tracers
.TP
.B \-t, \-\-threads[=NUM]
Set the number of test threads (default is 1). Create NUM test threads. If NUM is not specified, NUM is set to
the number of available CPUs. See \-d, \-i and \-p for further information.
.TP
.B \-m, \-\-mlockall
Lock current and future memory allocations to prevent being paged out
.TP
.B \-v, \-\-verbose
Output values on stdout for statistics. This option is used to gather statistical information about the latency distribution. The output is sent to stdout. The output format is:

n:c:v

where n=task number c=count v=latency value in us. Use this option in combination with \-l
.TP
.B \\-D, \-\-duration=TIME
Run the test for the specified time, which defaults to seconds. Append 'm', 'h', or 'd' to specify minutes, hours or days
.TP
.B \\-w, \-\-wakeup 
task wakeup tracing (used with \-b)
.TP
.B \\-W, \-\-wakeuprt
rt-task wakeup tracing (used with \-b)
.TP
.B \\-y, \-\-policy=NAME
set the scheduler policy of the measurement threads 
where NAME is one of: other, normal, batch, idle, fifo, rr
.TP
.B \\-M, \-\-refresh_on_max
delay updating the screen until a new max latency is hit (useful for
running cyclictest on low-bandwidth connections)
.TP
.B \\-S, \-\-smp
Set options for standard testing on SMP systems. Equivalent to using
the options: "\-t \-a \-n" as well keeping any specified priority
equal across all threads 
.\" .SH SEE ALSO
.\" .BR bar (1),
.\" .BR baz (1).
.\" .br
.\" The programs are documented fully by
.\" .IR "The Rise and Fall of a Fooish Bar" ,
.\" available via the Info system.
.SH AUTHOR
cyclictest was written by Thomas Gleixner <tglx@linuxtronix.de>.
.PP
This manual page was written by Alessio Igor Bogani <abogani@texware.it>,
for the Debian project (but may be used by others).
