.\"                                      Hey, EMACS: -*- nroff -*-
.TH HWLATDETECT 8 "May  12, 2009"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
hwlatdetect \- program to control the kernel SMI detection module
.SH SYNOPSIS
.B hwlatdetect
.RI "[ \-\-duration=<time> ] [\-\-threshold=<usecs> ] \
[\-\-interval=<msecs> ] [\-\-sample_width=<msecs> ] [\-\-report=<path> ] \
[\-\-cleanup ] [\-\-debug ] [\-\-quiet ]

.\" .SH DESCRIPTION
.\" This manual page documents briefly the
.\" .B hwlatdetect commands.
.\" .PP
.\" \fI<whatever>\fP escape sequences to invode bold face and italics, respectively.
.\" \fBhwlatdetect\fP is a program that...
.SH DESCRIPTION
\fBhwlatdetect\fP is a program that controls the SMI detector kernel
module (smi_detector.ko), provided with a realtime Linux kernel. The
module is used to detect the presence of System Management Interrupts
(SMI) which in some cases cause unexplained latencies. SMIs are generally
handled by BIOS code, not Linux kernel code and so cause unexpected
gaps in time.

The SMI kernel module runs a function that polls the TSC register
under the \fBstop_machine()\fP kernel function, looking for gaps in
time. Any gap that exceeds the specified input threshold is considered
to be the result of an SMI.

.SH OPTIONS
.TP
.B \-\-duration=<time>[smhd]
Run the detector logic in for the specified duration. The duration is
a base 10 integer number that defaults to a value in seconds. An
optional suffix may be specified to indicate minutes, hours or days.

.TP
.B \-\-threshold=<microsecond value>
Specify the TSC gap used to detect an SMI. Any gap value greater than
<theshold> is considered to be the result of an SMI occuring. 

.TP
.B \-\-interval=<millisecond value>
specify the interval between sample windows in milliseconds

.TP
.B \-\-sample_width=<millisecond value>
Specify the amount of time the kernel logic will run the detector
function, as a millisecond value
context switch tracing (used with \-b)
.TP
.B \-\-report=FILENAME
Specify the output filename of the SMI detector report. Default
behavior is to print to standard output
.TP
.B \-\-cleanup
Force unload of smi_detector.ko and unmounting of debugfs filesystem.
.TP
.B \-\-debug
Turn on debug prints
.TP
.B \-\-quiet
Turn off all information prints
.\" .SH SEE ALSO
.\" .BR bar (1),
.\" .BR baz (1).
.\" .br
.\" The programs are documented fully by
.\" .IR "The Rise and Fall of a Fooish Bar" ,
.\" available via the Info system.
.SH AUTHOR
.B hwlatdetect
.R was written by Clark Williams <williams@redhat.com>
