.\"
.TH SIGNALTEST 8 "November 15, 2020"
.\" Please adjust this date whenever updating this manpage
.SH NAME
signaltest \- signal roundtrip test software
.SH SYNOPSIS
.LP
signaltest [ -a|--affinity NUM] [ -b|--backtrace USEC ] [-D|--duration TIME] [-h|--help] [-l|--loops LOOPS ] [-p|--prio PRIO] [-q|--quiet] [-S|--smp] [-t|--threads NUM] [-m|--mlockall ] [-v|--verbose ]
.SH OPTIONS
These programs follow the usual GNU command line syntax, with long options
starting with two dashes ('\-\-').
.TP
.B \-a, \-\-affinity[=PROC-SET]
Run threads on the set of processors given by PROC-SET.  If PROC-SET is not
specified, all processors will be used.  Threads will be assigned to processors
in the set in numeric order, in a round\-robin fashion.
.br
The set of processors can be specified as A,B,C, or A-C, or A-B,D-F, and so on*.
The ! character can be used to negate a set.  For example, !B-D means to use all
available CPUs except B through D.  The cpu numbers are the same as shown in the
.I processor
field in /proc/cpuinfo.  See numa(3) for more information on specifying CPU sets.
* Support for CPU sets requires libnuma version >= 2.  For libnuma v1, PROC-SET,
if specified, must be a single CPU number.
.TP
.B \-b, \-\-breaktrace=USEC
Send break trace command when latency > USEC
.TP
.B \-D, \-\-duration=TIME
Specify a length for the test run.
.br
Append 'm', 'h', or 'd' to specify minutes, hours or days.
.TP
.B \-\-help
.br
display usage information
.TP
.B \-l, \-\-loops=LOOPS
Number of loops: default=0 (endless)
.TP
.B \-p, \-\-priority=PRIO
Priority of highest priority thread
.TP
.B \-q, \-\-quiet
print a summary only on exit
.TP
.B \\-S, \-\-smp
Set options for standard testing on SMP systems. Equivalent to using
the options: "\-t \-a" as well keeping any specified priority
equal across all threads
.TP
.B \-t, \-\-threads=NUM
number of threads: default=2
.TP
.B \-m, \-\-mlockall
lock current and future memory allocations
.TP
.B \-v, \-\-verbose
output values on stdout for statistics
.br
format: n:c:v n=tasknum c=count v=value in us
.SH AUTHOR
signaltest was written by Thomas Gleixner <tglx@linuxtronix.de>.
.PP
This manual page was originally written by
.br
John Kacur <jkacur@redhat.com>
.PP
Copying and distribution of this file, with or without modification,
are permitted in any medium without royalty provided the copyright
notice and this notice are preserved.  This file is offered as-is,
without any warranty.
