.\"                                      Hey, EMACS: -*- nroff -*-
.TH QUEUELAT 8 "Sept 3, 2018"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
queuelat \- Queue latency test program
.SH SYNOPSIS
.LP
queuelat [-c|--cycles N] [-f|--freq F] [-h|--help] [-m|--max-len LEN] [-p|--packets F] [-q|--queue-len N] [-t|--timeout TIME]
.SH DESCRIPTION
queuelat simulates a network queue checking for latency
violations in packet processing.

.SH OPTIONS
A summary of options is included below.
.TP
.B \-c, \-\-cycles=N
Estimated number of cycles it takes to process one packet. This value should come from the envisioned packet forwarding application being simulated.
.TP
.B \-f, \-\-freq=F
TSC frequency in MHz.
.TP
.B \-h, \-\-help
Show help
.TP
.B \-m, \-\-max-len=N
Maximum allowed latency, in nanoseconds. If latency to process any packet exceeds this value, the program quits, writing a message to the trace buffer.
.TP
.B \-p, \-\-packets=F
Million packets per second that arrive for processing.
.TP
.B \-q, \-\-queue-len=N
Minimum queue length to print in the trace
.TP
.B \-t, \-\-timeout=TIME
Timeout in seconds to quit the program.

.SH AUTHOR
queuelat was written by Marcelo Tosatti <mtosatti@redhat.com>
.br
