.\"                                      Hey, EMACS: -*- nroff -*-
.TH CYCLICDEADLINE 8 "January 16, 2020"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
cyclicdeadline \- This program is used to test the deadline scheduler (SCHED_DEADLINE) using a cyclictest style program
.PP
.SH SYNOPSIS
.B cyclicdeadline
.RI "[-ha] [-c cpulist] [-i interval] [-s step] [-t nr_threads] [-D duration]
.PP
.SH DESCRIPTION
.B cyclicdeadline
is a cyclictest style program for testing the deadline scheduler
.PP
.SH OPTIONS
.TP
.B \-h
Show this help menu
.TP
.B \-a
Use all CPUs
.TP
.B \-c cpulist
Comma / hypen separated list of CPUs to run deadline tasks on
.TP
.B \-i interval
The shortest deadline for the tasks in us. (default 1000us)
.TP
.B \-s step
The amount to increase the deadline for each task in us. (default 500us)
.TP
.B \-t nr_threads
The number of threads to run as deadline (default 1)
.TP
.B \-D time
Specify a length for the test to run
.br
Append 'm', 'h', or 'd' to specify minutes, hours, or days
.SH AUTHOR
cyclicdeadline was written by Steven Rostedt <rostedt@goodmis.org>
.PP
This manual page was written by John Kacur <jkacur@redhat.com>
