.\"                                      Hey, EMACS: -*- nroff -*-
.TH DEADLINE_TEST 8 "November 1, 2018"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
deadline_test \- High resolution test program
.SH DESCRIPTION
.PP
This program is used to test the deadline scheduler (SCHED_DEADLINE tasks)
.SH SYNOPSIS
.B deadline_test
.RI "[ \-hb ] [ \-c CPUSET ] [ \-i INTV ] [ \-p PERCENT ] [ \-P PERCENT ] \
[ \-r PRIO ]  [ \-s STEP ] [ \-t NUM ]"
.SH OPTIONS
.TP
.B \-b
Bind on the last cpu. (shortcut for -c <lastcpu>)
.br
.TP
.B \-c CPUSET
Comma/hyphen separated list of CPUs to run deadline tasks on
.br
.TP
.B \-h
Show this help menu
.br
.TP
.B \-i INTV
The shortest deadline for the tasks
.br
.TP
.B \-p PERCENT
The percent of bandwidth to use (1-90%)
.br
.TP
.B \-P PERCENT
The percent of runtime for execution completion (default 100%)
.br
.TP
.B \-r PRIO
Add an RT task with given prio to stress system
.br
.TP
.B \-s STEP
The amount to increase the deadline for each task in us (default 500us)
.br
.TP
.B \-t NUM
The number of threads to run as deadline (default 1)
.br
.SH AUTHOR
Deadline test was written by Steven Rostedt <rostedt@goodmis.org>
.PP
This manual page was written by John Kacur <jkacur@redhat.com>
